import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {OngoingUsage} from '../src/ongoing-usage.js';
import {CodexDecisionBackend,LUNA_MODEL,parseCodexChoice,codexRequest} from '../src/codex-decision.js';
const view:any={pawn:{id:'A'},character:{id:'A'},question:{id:'q',from:'core',text:'Food?'}};
function fixture(code:string){const root=mkdtempSync(join(tmpdir(),'luna-test-'));writeFileSync(join(root,'catalog.json'),'{}');writeFileSync(join(root,'helper.py'),code);const b=new CodexDecisionBackend({ledgerPath:join(root,'usage.db'),scratchRoot:join(root,'scratch'),catalogPath:join(root,'catalog.json'),helperPath:join(root,'helper.py')});return {root,b,close(){b.close();rmSync(root,{recursive:true,force:true});}};}
const helper=(raw:any)=>`import sys,pathlib,json\np=pathlib.Path(sys.argv[3]);p.mkdir()\n(p/'result.json').write_text(json.dumps(${JSON.stringify(JSON.stringify(raw))} and json.loads(${JSON.stringify(JSON.stringify(raw))})))\n`;
const receipt={status:'completed',stage:'completed',model:LUNA_MODEL,preflight:{requests:1,toolsExposed:0},usage:{inputTokens:10,cachedInputTokens:0,outputTokens:4,reasoningOutputTokens:0,totalTokens:14},rawText:JSON.stringify({social:{choice:'say',text:'Only testimony'}})};
test('native backend accepts the same typed pawn choice and retains subscription tokens without fake cash',async()=>{const f=fixture(helper(receipt));try{assert.deepEqual(await f.b.answerCore(view,new AbortController().signal),{choice:'say',text:'Only testimony'});assert.equal(f.b.summary().attempts,1);assert.equal(f.b.summary().rows[0]!.status,'ok');assert.equal(f.b.receipts[0].usage.totalTokens,14);assert(!JSON.stringify(f.b.summary()).includes('costUSD'));}finally{f.close();}});
test('wrong model, exposed tools and invalid output fail without reroll; failed attempts persist',async()=>{for(const change of [{model:'other'},{preflight:{requests:1,toolsExposed:1}},{rawText:JSON.stringify({social:{choice:'order',pawn:'B'}})}]){const f=fixture(helper({...receipt,...change}));try{await assert.rejects(f.b.answerCore(view,new AbortController().signal));assert.equal(f.b.summary().rows[0]!.status,'failed');assert.equal(f.b.receipts.length,1);}finally{f.close();}}});
test('cancellation kills helper descendants, prevents late output, and settles the reservation',async()=>{const f=fixture(`import subprocess,sys,pathlib,time\np=pathlib.Path(sys.argv[3]);p.mkdir()\nc=subprocess.Popen(['python3','-c','import time;time.sleep(60)'])\n(p.parent.parent.parent/'pid').write_text(str(c.pid))\ntime.sleep(60)\n`);try{const ctl=new AbortController(),job=f.b.answerCore(view,ctl.signal);job.catch(()=>{});let pid=0;for(let i=0;i<100;i++){try{pid=Number(readFileSync(join(f.root,'pid'),'utf8'));break;}catch{}await new Promise(r=>setTimeout(r,10));}assert(pid);ctl.abort();await assert.rejects(job);assert.equal(f.b.summary().rows[0]!.status,'cancelled');try{const status=readFileSync('/proc/'+pid+'/stat','utf8');assert.match(status,/\) Z /);}catch(e){if((e as any).code!=='ENOENT')throw e;}}finally{f.close();}});
test('ongoing ledger has no turn ceiling but crash uncertainty and repeated failures stop admission',()=>{const root=mkdtempSync(join(tmpdir(),'usage-test-')),file=join(root,'u.db');let u=new OngoingUsage(file);try{for(let i=0;i<25;i++)u.settle(u.reserve('core',LUNA_MODEL),'ok',1,null);const pending=u.reserve('core',LUNA_MODEL);u.close();u=new OngoingUsage(file);assert.throws(()=>u.reserve('core',LUNA_MODEL),/Unresolved/);u.settle(pending,'cancelled',1,null);for(let i=0;i<2;i++)u.settle(u.reserve('core',LUNA_MODEL),'failed',1,null);assert.throws(()=>u.reserve('core',LUNA_MODEL),/Repeated/);assert.equal(u.summary().length,28);}finally{u.close();rmSync(root,{recursive:true,force:true});}});
test('ongoing policy refuses a historical ledger instead of changing it',()=>{const root=mkdtempSync(join(tmpdir(),'old-usage-')),file=join(root,'old.db'),db=new DatabaseSync(file);db.exec('CREATE TABLE reservations(id TEXT)');db.close();assert.throws(()=>new OngoingUsage(file),/Not an ongoing/);rmSync(root,{recursive:true,force:true});});
test('Luna JSON wrapper is strict, not prose-extracted action authority',()=>{assert.throws(()=>parseCodexChoice('core-answer','I will eat',view));assert.throws(()=>parseCodexChoice('core-answer',JSON.stringify({social:{choice:'say',text:'Hi'},order:'eat'}),view));});

test('native structured-output dialect applies to live modes, not just offline suites',()=>{
 const req=codexRequest('core-answer',view);const text=JSON.stringify(req.schema);
 assert(!text.includes('"const"'));assert(!text.includes('"oneOf"'));assert(!text.includes('"uniqueItems"'));assert(text.includes('"enum"'));
});
