Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "AutoEnableDevices" "false"
    Option "DontVTSwitch" "true"
EndSection
Section "Device"
    Identifier "VirtualGPU"
    Driver "modesetting"
    Option "AccelMethod" "glamor"
EndSection
Section "Screen"
    Identifier "LabScreen"
    Device "VirtualGPU"
    DefaultDepth 24
EndSection
